{
 "title": "Locust Requests Dashboard (stats-otel plugin)",
 "description": "Locust Requests Dashboard (stats-otel plugin)",
 "time": { "from": "2025-09-19T08:05:50.513Z", "to": "2025-09-19T08:07:20.390Z" },
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run Id",
    "query": {
     "query": "label_values(locust_tl_locust_event_test_total,run_id)"
    }
   },
   {
    "name": "testplan",
    "label": "Test Plan",
    "query": {
     "query": "label_values(locust_tl_locust_event_test_total,testplan)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Load Testing Requests Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Request Response Time",
   "type": "timeseries",
   "description": "Average Request Response Time",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(source_id) (rate(locust_tl_request_metric_stats_milliseconds_sum{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])) / sum by(source_id) (rate(locust_tl_request_metric_stats_milliseconds_count{run_id=~\"$run_id\"}[$__rate_interval]))",
     "legendFormat": "{{source_id}}"
    }
   ]
  },
  {
   "title": "Max FPS",
   "type": "gauge",
   "description": "Max FPS",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "f/s" } },
   "targets": [
    {
     "expr": "max(sum(rate(locust_tl_request_metric_stats_milliseconds_count{exception=\"true\", run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max RPS",
   "type": "gauge",
   "description": "Max RPS",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "max(sum(rate(locust_tl_request_metric_stats_milliseconds_count{exception=\"false\", run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "description": "Response Time Percentiles",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(locust_tl_request_metric_stats_milliseconds_bucket{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(locust_tl_request_metric_stats_milliseconds_bucket{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(locust_tl_request_metric_stats_milliseconds_bucket{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "gauge",
   "description": "Virtual Users",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "#" } },
   "targets": [
    {
     "expr": "last_over_time(locust_tl_user_metric_stats_ratio{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS vs FPS",
   "type": "timeseries",
   "description": "RPS vs FPS",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "sum(rate(locust_tl_request_metric_stats_milliseconds_count{exception=\"false\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(locust_tl_request_metric_stats_milliseconds_count{exception=\"true\"}[$__rate_interval]))",
     "legendFormat": "FPS"
    }
   ]
  },
  {
   "title": "Request Success vs Failure (%)",
   "type": "timeseries",
   "description": "Request Success (%)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(locust_tl_request_metric_stats_milliseconds_count{exception=\"false\", run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))\n/\nsum(rate(locust_tl_request_metric_stats_milliseconds_count{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))) * 100",
     "legendFormat": "Success %"
    },
    {
     "expr": "(sum(rate(locust_tl_request_metric_stats_milliseconds_count{exception=\"true\", run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))\n/\nsum(rate(locust_tl_request_metric_stats_milliseconds_count{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))) * 100",
     "legendFormat": "Failure %"
    }
   ]
  },
  {
   "title": "Request Success vs Failures",
   "type": "timeseries",
   "description": "Request Success vs Failures",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "#" } },
   "targets": [
    {
     "expr": "sum(locust_tl_request_metric_stats_milliseconds_count{exception=\"false\", run_id=~\"$run_id\", testplan=~\"$testplan\"})",
     "legendFormat": "# Success"
    },
    {
     "expr": "sum(locust_tl_request_metric_stats_milliseconds_count{exception=\"true\", run_id=~\"$run_id\", testplan=~\"$testplan\"})",
     "legendFormat": "# Failures"
    }
   ]
  },
  {
   "title": "User Ramp Rate",
   "type": "timeseries",
   "description": "User Ramp Rate",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "deriv(locust_tl_user_metric_stats_ratio{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval])",
     "legendFormat": "Ramp Rate"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "timeseries",
   "description": "User Count",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "locust_tl_user_metric_stats_ratio{run_id=~\"$run_id\", testplan=~\"$testplan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users vs RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "#" } },
   "targets": [
    {
     "expr": "locust_tl_user_metric_stats_ratio{run_id=~\"$run_id\", testplan=~\"$testplan\"}",
     "legendFormat": "# Users"
    },
    {
     "expr": "sum(rate(locust_tl_request_metric_stats_milliseconds_count{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Avg Response Time By Endpoint",
   "type": "timeseries",
   "description": "Response Time By Endpoint",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (\n  rate(locust_tl_request_metric_stats_milliseconds_sum[$__rate_interval])\n)\n/\nsum by (endpoint) (\n  rate(locust_tl_request_metric_stats_milliseconds_count[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Usage of master and worker nodes",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (source_id) (locust_tl_system_metric_cpu_percent{run_id=~\"$run_id\", testplan=~\"$testplan\"})",
     "legendFormat": "{{source_id}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "gauge",
   "description": "Network Usage",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (source_id) (last_over_time(locust_tl_system_metric_mem_bytes{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Usage",
   "type": "gauge",
   "description": "Max CPU Usage",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (source_id) (last_over_time(locust_tl_system_metric_cpu_percent{run_id=~\"$run_id\", testplan=~\"$testplan\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory Usage of master and worker nodes",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum by (source_id) (locust_tl_system_metric_mem_bytes{run_id=~\"$run_id\", testplan=~\"$testplan\"})",
     "legendFormat": "{{source_id}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "Network Usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (source_id) (locust_tl_system_metric_network_bytes{run_id=~\"$run_id\", testplan=~\"$testplan\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}