{
 "title": "Locust Requests Dashboard",
 "description": "Dashboard for locust core metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testplan",
    "label": "Test Plan",
    "query": {}
   },
   {
    "name": "run_id",
    "label": "Run Id",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Application Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests / Failures",
   "type": "timeseries",
   "description": "Number of requests",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.current.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "description": "Total Requests",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.final.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Rate of Requests / Failures",
   "type": "timeseries",
   "description": "Request rate vs Failure Rates",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.current.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Total Failures",
   "type": "gauge",
   "description": "Total Failures",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.final.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "timeseries",
   "description": "Average Response Time",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.current.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Response time (min)",
   "type": "stat",
   "description": "Min Response Time",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.final.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "timeseries",
   "description": "User count over time",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.current.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Response time (max)",
   "type": "stat",
   "description": "Max Response Time",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.final.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  { "title": "Endpoint Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Endpoint Statistics",
   "type": "table",
   "description": "Endpoint Statistics",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.endpoint.stats\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Endpoint Errors",
   "type": "table",
   "description": "Endpoint Errors",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.request.endpoint.errors\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  }
 ]
}