{
 "title": "Locust Requests Dashboard (stats-json plugin)",
 "description": "Dashboard for locust core metrics for stats-json plugin",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testplan",
    "label": "Test Plan",
    "query": {}
   },
   {
    "name": "run_id",
    "label": "Run Id",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Application Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "gauge",
   "description": "Total Requests",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Minimum Response Time",
   "type": "stat",
   "description": "Minimum Response Time",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Total Failures",
   "type": "gauge",
   "description": "Total Failures",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "gauge",
   "description": "Total Requests Per Second",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Maximum Response Time",
   "type": "stat",
   "description": "Maximum Response Time",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Failure Per Second",
   "type": "gauge",
   "description": "Failure Per Second",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "f/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Total Requests / Failures",
   "type": "timeseries",
   "description": "Number of requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.current\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Rate of Requests / Failures",
   "type": "timeseries",
   "description": "Request rate vs Failure Rates",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.current\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "timeseries",
   "description": "Average Response Time",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.current\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "timeseries",
   "description": "User count over time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.current\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Endpoint's Average Response Time",
   "type": "bargauge",
   "description": "Endpoint's Average Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final.success\", testplan=~\"$testplan\", run_id=~\"$run_id\"}"
    }
   ]
  },
  {
   "title": "Endpoint's FPS",
   "type": "bargauge",
   "description": "Endpoint's Failures Per Second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final.success\", testplan=~\"$testplan\", run_id=~\"$run_id\"}"
    }
   ]
  },
  { "title": "Endpoint Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Endpoint Statistics",
   "type": "table",
   "description": "Endpoint Statistics",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final.success\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Endpoint Errors",
   "type": "table",
   "description": "Endpoint Errors",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-master\", telemetry_name=\"metric.requests.stats.final.errors\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  { "title": "Load testing Node Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU Usage Profile",
   "type": "timeseries",
   "description": "Master and Nodes CPU Usages Profile",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"locust-master|locust-worker\", telemetry_name=\"metric.system.cpu\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Total Workers",
   "type": "stat",
   "description": "Total Workers",
   "gridPos": { "h": 13, "w": 4, "x": 10, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"locust-worker\", telemetry_name=\"metric.system.cpu\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "timeseries",
   "description": "Master and Nodes Memory Profile",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"locust-master|locust-worker\", telemetry_name=\"metric.system.mem\", testplan=~\"$testplan\", run_id=~\"$run_id\"}\n| json"
    }
   ]
  }
 ]
}